//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIS4396Solution
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadFile
    {
        public int FileId { get; set; }
        public int PortfolioId { get; set; }
        public string FileNm { get; set; }
        public string FileType { get; set; }
        public byte[] UploadFile1 { get; set; }
        public string ActiveInd { get; set; }
        public Nullable<System.DateTime> LastModDt { get; set; }
        public string LastModUser { get; set; }
        public Nullable<System.DateTime> CreateDt { get; set; }
        public string CreateUserNm { get; set; }
        public string ItemType { get; set; }
    }
}
